- name: Instalar K3s Master no master
  ansible.builtin.shell: |
    set -e
    curl -sfL https://get.k3s.io | K3S_TOKEN="{{ K3S_TOKEN }}" sh -s - server \
    --write-kubeconfig-mode 644 \
    --node-name {{ inventory_hostname }}
  args:
    creates: /usr/local/bin/k3s

- name: Aguardar API do Kubernetes subir
  wait_for:
    host: 127.0.0.1
    port: 6443
    delay: 5
    timeout: 60
